import type { Metadata } from "next";
import {
  Montserrat
} from "next/font/google";
import "../styles/globals.scss";
import Container from "@/components/Layout/Container/Container";
import BackgroundEffect from "@/components/BackgroundEffect/BackgroundEffect";
import Header from "@/components/Layout/Header/Header";
import MobileMenu from "@/components/Layout/MobileMenu/MobileMenu";

const notoSans = Montserrat({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Ivgam | Artyom Galay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  locale,
}: Readonly<{
  children: React.ReactNode;
  locale: never;
}>) {
  return (
		<html lang={locale}>
			<body className={notoSans.className}>
				<Container>
					<Header />
					<BackgroundEffect />
          <MobileMenu />
					{children}
				</Container>
			</body>
		</html>
	);
}
