import type { Metadata } from "next";
import {Codystar, Noto_Sans, Gowun_Dodum, Noto_Sans_Mono, Noto_Sans_Display, Nokora} from "next/font/google";
import "../styles/globals.scss"

const notoSans = Nokora({
  subsets: [ "latin",],
  weight: [ "400", "700"]
 
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  locale
}: Readonly<{
  children: React.ReactNode;
  locale: never;
}>) { 
  return (
    <html lang="en">
      <body className={notoSans.className}>{children}</body>
    </html>
  );
}
