import type { Metadata } from "next";
import {  Noto_Sans } from "next/font/google";
import "../styles/globals.css"

const notoSans = Noto_Sans({
  subsets: ["cyrillic", "latin"],
 
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  locale
}: Readonly<{
  children: React.ReactNode;
  locale: never;
}>) { 
  return (
    <html lang="en">
      <body className={notoSans.className}>{children}</body>
    </html>
  );
}
